name: "ELTOROIT CICD Test Scratch Org"
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            ET_CICD: true
        steps:
            # Setup the Vitual Machine
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Show Node.js version
              run: node -v
            - name: Create etLogs folder
              run: mkdir -p etLogs
            - name: Export token
              run: echo ${{secrets.DEVHUB_TOKEN}} > etLogs/token.txt
            - name: Install Salesforce tools
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz -q
                  mkdir sfdx-cli
                  tar xJf sfdx-linux-x64.tar.xz -C sfdx-cli --strip-components 1
                  ./sfdx-cli/install
                  sfdx update
                  sfdx force:lightning:lwc:test:setup
            - name: Install ETCopyData tools
              # run: echo 'y' | sfdx plugins:install etcopydata@beta
              run: |
                  git clone https://github.com/eltoroit/ETCopyData.git
                  cd ETCopyData
                  npm install
                  sfdx plugins:link
                  cd ..
            - name: Register DevHub
              run: sfdx force:auth:sfdxurl:store -f "etLogs/token.txt" --setalias DevHub --setdefaultdevhubusername
            # Create scratch org
            - name: Create Scratch Org
              run: node ./@ELTOROIT/scripts/nodejs/orgBuilder.mjs
            # Upload logs as artifacts
            - uses: actions/upload-artifact@v2
              with:
                  name: logs
                  path: |
                      etLogs
                      !etLogs/token.txt
